# Advanced Performance Monitoring Stack
apiVersion: v1
kind: ConfigMap
metadata:
  name: performance-monitoring-config
  namespace: cybersecurity-capstone
data:
  # Prometheus Configuration
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - "security_rules.yml"
      - "performance_rules.yml"
    
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
      
      - job_name: 'security-scanner'
        static_configs:
          - targets: ['security-scanner:8080']
      
      - job_name: 'penetration-testing'
        static_configs:
          - targets: ['pentest-env:9090']
  
  # Grafana Dashboard Configuration
  dashboard.json: |
    {
      "dashboard": {
        "title": "Cybersecurity Capstone Monitoring",
        "panels": [
          {
            "title": "Security Scan Performance",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(security_scans_total[5m])",
                "legendFormat": "Scans/sec"
              }
            ]
          },
          {
            "title": "Vulnerability Detection Rate",
            "type": "stat",
            "targets": [
              {
                "expr": "vulnerabilities_detected_total",
                "legendFormat": "Total Vulnerabilities"
              }
            ]
          },
          {
            "title": "System Resource Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(container_cpu_usage_seconds_total[5m])",
                "legendFormat": "CPU Usage"
              },
              {
                "expr": "rate(container_memory_usage_bytes[5m])",
                "legendFormat": "Memory Usage"
              }
            ]
          }
        ]
      }
    }
  
  # Jaeger Configuration
  jaeger-config.yaml: |
    collector:
      zipkin:
        http-port: 9411
    query:
      base-path: /jaeger
    agent:
      zipkin:
        http-port: 9411
