# Deployment for Penetration Testing Environment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pentest-env
  namespace: cybersecurity-capstone
  labels:
    app: pentest-env
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pentest-env
  template:
    metadata:
      labels:
        app: pentest-env
        version: v1.0.0
    spec:
      containers:
      - name: pentest-container
        image: cybersecurity-capstone:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: TARGET_IP
          valueFrom:
            configMapKeyRef:
              name: pentest-config
              key: TARGET_IP
        - name: TARGET_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: pentest-config
              key: TARGET_DOMAIN
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: pentest-config
              key: LOG_LEVEL
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pentest-secrets
              key: DB_PASSWORD
        volumeMounts:
        - name: reports-volume
          mountPath: /app/reports
        - name: logs-volume
          mountPath: /app/logs
        - name: wordlists-volume
          mountPath: /app/wordlists
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: reports-volume
        persistentVolumeClaim:
          claimName: reports-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: logs-pvc
      - name: wordlists-volume
        configMap:
          name: wordlists-config
---
# Service for Penetration Testing Environment
apiVersion: v1
kind: Service
metadata:
  name: pentest-service
  namespace: cybersecurity-capstone
  labels:
    app: pentest-env
spec:
  selector:
    app: pentest-env
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pentest-hpa
  namespace: cybersecurity-capstone
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pentest-env
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
